// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0sUM35I7_BZqY3m_0TI1t41-kIf0eiIs',
    appId: '1:978832820668:web:94c52d66e28f16431483b9',
    messagingSenderId: '978832820668',
    projectId: 'climate-care-3ae71',
    authDomain: 'climate-care-3ae71.firebaseapp.com',
    databaseURL: 'https://climate-care-3ae71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'climate-care-3ae71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMMi0b8rN9NMVicMUWXbswcDHIQykndv8',
    appId: '1:978832820668:android:6a8861ce7a37b9071483b9',
    messagingSenderId: '978832820668',
    projectId: 'climate-care-3ae71',
    databaseURL: 'https://climate-care-3ae71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'climate-care-3ae71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgy2i4L76o0ruI7AZW5qQrtyAvMx4Zrp4',
    appId: '1:978832820668:ios:52cb164519c232921483b9',
    messagingSenderId: '978832820668',
    projectId: 'climate-care-3ae71',
    databaseURL: 'https://climate-care-3ae71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'climate-care-3ae71.appspot.com',
    iosClientId: '978832820668-r0sjesr04i7581aodf0il7p8ugm1pu0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.climateTce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgy2i4L76o0ruI7AZW5qQrtyAvMx4Zrp4',
    appId: '1:978832820668:ios:52cb164519c232921483b9',
    messagingSenderId: '978832820668',
    projectId: 'climate-care-3ae71',
    databaseURL: 'https://climate-care-3ae71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'climate-care-3ae71.appspot.com',
    iosClientId: '978832820668-r0sjesr04i7581aodf0il7p8ugm1pu0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.climateTce',
  );
}
